### ISSUE TITLE
AssertArray withKey wrong path

### ISSUE THREAD

**Issue by marcel-benthin** [philiagus/parser#3]
Shouldn’t [AssertArray.php:215](https://github.com/philiagus/parser/blob/master/src/Philiagus/Parser/Parser/AssertArray.php#L215) be `$path->key($key)`?

**Comment by philiagus** [comment]
@marcel-benthin The path of the exception usually points to the location of the error in the parsed structure/value. The provided structure - in this case an array - does not contain this value, so it is not a mistake of the key which is missing, as it is not there, but rather a mistake of the array to not have the required key.

What are your thoughts on this?

**Comment by marcel-benthin** [comment]
Yeah, if you want to interpret it that way. I would be more in favor of seeing it as: That the mistake of a missing key is at the position of that key.
In the sense of “I was looking **at** key” instead “I was looking **for** key”, because `withKey(…)` implies for me that I’m looking for something at a particular place (key).

But your point of view is also valid for me, so let’s go with the authors intention.
